apiVersion: v1
kind: Service
metadata:
  name: donaton-frontend
  namespace: donaton
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: donaton-frontend
  ports:
    - port: 80
      targetPort: 80
